### PR TITLE
[terra-functional-testing] Fix selenium docker version service option

### LINKED ISSUE #596: [terra-functional-testing] Fix selenium docker version service option
# Bug Report

## Description

The selenium docker version option should be deconstructed from the `serviceOptions` in the configuration object. It is currently being deconstructed from the `launcherOptions`. 

https://github.com/cerner/terra-toolkit/blob/28f4e2d9c0339b01db3a70990f66e187e56835c1/packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js#L21

```js
// Deconstruct from the serviceOptions
 const { launcherOptions, serviceOptions } = config;
 const { disableSeleniumService, keepAliveSeleniumDockerService } = launcherOptions || {};
 const { version } = serviceOptions || {};
```

This can be tested by updating the selenium docker version in the serviceOptions override and verifying docker pulls down the expected image.

```js
// wdio.conf.js
const { config } = require('@cerner/terra-functional-testing/lib/config/wdio.conf');

config.serviceOptions = {
  version: 'new version',
};

exports.config = config;
```

### PR DESCRIPTION
**Pull request by StephenEsser**
### Summary

This PR fixes the API for specifying the docker version option. `version` should be deconstructed from `serviceOptions` instead of `launcherOptions`.

Fixes #596.

### Additional Details

Since this wasn't working as expected on the 1.0.0 release we could rename this option if we wanted to. 

@cerner/terra

[CONTRIBUTORS.md]: ../blob/main/CONTRIBUTORS.md
[License]: ../blob/main/LICENSE

### CODE REVIEW

File: packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js [hunk 1]
```diff
@@ -17,8 +17,9 @@ class SeleniumDockerService {
    * @param {Object} config - The object containing the wdio configuration and options defined in the terra-cli test runner.
    */
   constructor(_options, _capabilities, config = {}) {
-    const { launcherOptions } = config;
-    const { disableSeleniumService, keepAliveSeleniumDockerService, version } = launcherOptions || {};
+    const { launcherOptions, serviceOptions } = config;
+    const { disableSeleniumService, keepAliveSeleniumDockerService } = launcherOptions || {};
+    const { version } = serviceOptions || {};
```
Comment (StephenEsser) [inline packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js:22]: Since this wasn't working as expected on the 1.0.0 release we could rename this option if we wanted to.

File: packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js [hunk 2]
```diff
@@ -92,14 +93,14 @@ class SeleniumDockerService {
 
     await exec(`${envVars}docker-compose -f ${this.getDockerComposeFilePath()} up -d`);
     await this.waitForSeleniumHubReady();
+
+    logger.info('Successfully started the docker selenium hub.');
```
Comment (StephenEsser) [inline packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js:97]: I added this log so we can see when the docker hub is active. Sometimes in large projects webpack takes a while to complete and because the last log was "starting docker..." it seems like it's waiting on docker, but it's actually waiting on webpack. This just adds verification the docker hub started.

File: packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js (hunk 1 above)
Comment (benbcai) [reply packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js:22]: We currently [read the selector](https://github.com/cerner/terra-toolkit/blob/28f4e2d9c0339b01db3a70990f66e187e56835c1/packages/terra-functional-testing/src/services/wdio-terra-service.js#L27) override from [serviceOptions](https://engineering.cerner.com/terra-ui/dev_tools/cerner/terra-functional-testing/wdio-services/terra-service#selector) so renaming it would be non-passive. Do consumers ever need to set the version? If so, should we add some documentation to show this is where to specify the version?

**Review by benbcai — APPROVED** [review]

File: packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js (hunk 1 above)
Comment (StephenEsser) [reply packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js:22]: Are you referring to renaming `serviceOptions` or `version`. My comment was regarding the name of `version`.

> Do consumers ever need to set the version?

`version` was added so that consumers could periodically update and test against newer selenium docker images. I don't think anyone is doing this today because we rarely update the internal grid, but as we start to make updates more frequently I think this option will become more adopted for testing. 

version is documented [here](https://engineering.cerner.com/terra-ui/dev_tools/cerner/terra-functional-testing/wdio-services/selenium-docker-service#version), but it's out of date now that we no longer accept constructor options. I'll add a note to the documentation update issue #595

Comment (benbcai) [reply packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js:22]: Sounds good. I thought you were referring to renaming `serviceOptions` so ignore my comment.

**Review by mjhenkes — APPROVED** [review]

File: packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js (hunk 1 above)
Comment (benbcai) [reply packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js:22]: Since `version` is no longer provided directly as a service option and is now defined at the flat config level, maybe it makes sense to give it a more descriptive name so that we know what this version refers to. (e.g. `seleniumDockerVersion`, `seleniumDockerImageVersion`, etc).

Comment (StephenEsser) [reply packages/terra-functional-testing/src/services/wdio-selenium-docker-service.js:22]: Whoops, I think I merged at the same time your comment came through. There's still time to update it before the release if we want to change it
