### PR TITLE
Ctrl-c wdio end process issue

### LINKED ISSUE #197: [tt-wdio] Gracefully Stop Executing with Killed
# Bug Report

## Description
Fix tt-wdio runner to honor `control + c` when attemping to kill & stop script execution. Currently it continues to loop the options provided or it does not correctly handle promise rejection when the process is killed via `control + c`. 

## Expected Behavior
`control + c` should stop the script correctly.

### PR DESCRIPTION
**Pull request by ryanthemanuel**
### Summary

This will gracefully exit the wdio runner when a ctrl-c happens.  Fixes #197

### CODE REVIEW

**Review by bjankord — APPROVED** [review]

**Review by emilyrohrbough — APPROVED** [review]

**Review by jmsv6d — APPROVED** [review]

File: scripts/wdio/wdio-runner.js [hunk 1]
```diff
@@ -19,12 +19,25 @@ async function wdioRunner(options) {
...
   for (let localeI = 0; localeI < testlocales.length; localeI += 1) {
     const locale = testlocales[localeI];
     process.env.LOCALE = locale;
 
     for (let factor = 0; factor < factors.length; factor += 1) {
       let envValues = `LOCALE=${locale} `;
+      let exitProcess = false;
+      process.on('SIGINT', () => {
+        exitProcess = true;
+        return exitProcess;
```
Comment (nramamurth) [inline scripts/wdio/wdio-runner.js]: Is this needed?

File: scripts/wdio/wdio-runner.js [hunk 2]
```diff
@@ -39,11 +52,11 @@ async function wdioRunner(options) {
         .run()
         .then(
           (code) => {
-            if (code === 1 && !continueOnFail) {
+            if (code === 1 && !continueOnFail && !exitProcess) {
```
Comment (nramamurth) [inline scripts/wdio/wdio-runner.js:56]: I think it's better to have an inline comment that explains this if-else block for future debugging (if necessary).

**Review by mjhenkes — APPROVED** [review]
