### PR TITLE
[terra-toolkit] Remove defaults from Aggregate Translations CLI options.

### LINKED ISSUE #257: Aggregate translations cli default options overriding config file
# Bug Report

## Description

tt-aggregate-translations cli default options override the options in the terraI18n.config.js file.

```
const defaultConfig = {
    baseDir: options.baseDir || config.baseDir || process.cwd(),
    directories: options.directories || config.directories || [],
    fileSystem: options.outputFileSystem || config.outputFileSystem || fse,
    locales: options.locales || config.locales || supportedLocales,
    outputDir: options.outputDir || './aggregated-translations',
    excludes: options.excludes || config.excludes || [],
    format: options.format,
  };
```
https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations.js#L32

```
const aggregationOption = {
  baseDirectory: commander.baseDir,
  directories: customSearchDirectories,
  exclude: customExcludeDirectories,
  locales: commander.locales,
  outputDir: commander.outputDir,
  configPath: commander.config,
  format: commander.format,
};
```
https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L31

## Steps to Reproduce

1. Create a terraI18n.config.js file and add some configuration
2. Run the aggregate translations cli using only the --config paramenter
3. The default config options override the options in the config file

## Expected Behavior

Config file options take precedence over default options.

## Environment

* Component Name and Version: tt-aggregate-translations v4.23.1
* Browser Name and Version: n/a
* Node/npm Version: Node 8.4.0/Npm 6.7.0
* Webpack Version: n/a
* Operating System and version (desktop or mobile): desktop

### LINKED ISSUE #264: 'exclude' option does not work via CLI as well as via the setup function.
# Bug Report

## Description
The [documentation](https://github.com/cerner/terra-toolkit/blob/master/docs/AggregateTranslations.md#order-of-operations) mentions that the option name is `exclude` and the [aggregate-translations-cli.js](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L27) does correctly parse the argument as `exclude`. The [aggregate-translations.js](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations.js#L38) however tries to look for `excludes` property in the config/options which will not exist. 

## Steps to Reproduce
1. Use the `exclude` option to glob exclude a set of directories from the search patterns.
2. Notice that the set of directories mentioned in Step 1 are included in the list of directories that are being searched for translations files.

## Expected Behavior
The directories matching the patterns set to the `exclude` option should be excluded from the default search list of directories.

## Possible Solutions
1. Change the option name from `exclude` to `excludes` [here](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L27) and [here](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations-cli.js#L34) and update the documentation. For more context, refer to https://github.com/cerner/terra-toolkit/issues/257#issuecomment-474805757. 
2. Keep the documentation and the options as-is and instead update the [line of code](https://github.com/cerner/terra-toolkit/blob/master/scripts/aggregate-translations/aggregate-translations.js#L38) to look for `exclude` instead of `excludes`. Refer to https://github.com/cerner/terra-toolkit/issues/264#issuecomment-475492131.

## Environment

* Component Name and Version: `terra-toolkit@4.25.0`
* Browser Name and Version: N/A
* Node/npm Version: [e.g. Node 8/npm 5]: Nodejs v8.15.1 AND npm v6.4.1
* Webpack Version: N/A
* Operating System and version (desktop or mobile): Desktop, MacOS. 

## @ Mentions

@emilyrohrbough @ryanthemanuel

### PR DESCRIPTION
**Pull request by nramamurth**
### Summary
Fixes #257. 
Fixes #264.

### Additional Details
1. The CLI options take precedence over the options mentioned in the configuration file (if one exists) if the consumer runs the CLI script. 
2. If the consumers specify a subset of CLI options, then the script
2.1. looks for the remaining options in the configuration file if one exists.
2.2. uses the default options if the configuration file does not exist.

https://github.com/cerner/terra-toolkit/blob/1015c35decebafad4135c231dd9a2bafdb6f2d8d/scripts/aggregate-translations/aggregate-translations.js#L32-L41

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
I was talking with Ryan in passing, what are your thoughts in moving the CLI defaults that have values to the help CLI help text so the default value isn't hidden for users?

For example:

```
.option('-l, --locales [locales]', `The list of locale codes aggregate on and combine into a single, respective translation file. Default: ${supportedLocales}`, parseCLIList)
```

**Comment by nramamurth** [comment]
> I was talking with Ryan in passing, what are your thoughts in moving the CLI defaults that have values to the help CLI help text so the default value isn't hidden for users?

@emilyrohrbough 💯 I missed out the fact the defaults are hidden with my change. It will look something similar to - 

Screen Shot 2019-03-22 at 9 38 49 AM

File: scripts/aggregate-translations/aggregate-translations-cli.js [hunk 1]
```diff
@@ -5,33 +5,22 @@ const parseCLIList = require('../utils/parse-cli-list');
...
   .version(i18nPackageJson.version)
-  .option('-b, --baseDir [baseDir]', 'The directory to start searching from and to prepend to the output directory', process.cwd())
-  .option('-d, --directories [directories]', 'Regex pattern to glob search for translations', addCustomDirectory)
-  .option('-l, --locales [locales]', 'The list of locale codes aggregate on and combine into a single, respective translation file ', parseCLIList, supportedLocales)
-  .option('-o, --outputDir [outputDir]', 'The output location of the generated configuration file', './aggregated-translations')
-  .option('-c, --config [configPath]', 'The path to the terra i18n configuration file', undefined)
-  .option('-e, --exclude [exclude]', 'Regex pattern to glob filter out directories', addCustomExclude)
-  .option('-f, --format [format]', 'Format to output the aggregated translations to. Options are [es5, es6]', 'es5')
+  .option('-b, --baseDir [baseDir]', `The directory to start searching from and to prepend to the output directory. Default: ${process.cwd()}`)
+  .option('-d, --directories [directories]', 'Regex pattern to glob search for translations. Default: []', parseCLIList)
```
Comment (emilyrohrbough) [inline scripts/aggregate-translations/aggregate-translations-cli.js]: Previously directories could be added like:
```bash
tt-aggregate-translations -d './translations' -d './custom_translations'
```
Does passing to parse parseCLIList change this behavior to:
```bash
tt-aggregate-translations -d ['./translations','./custom_translations']
```

File: scripts/aggregate-translations/aggregate-translations.js [hunk 2]
```diff
@@ -36,7 +36,7 @@ const defaults = (options = {}) => {
     locales: options.locales || config.locales || supportedLocales,
     outputDir: options.outputDir || './aggregated-translations',
     excludes: options.excludes || config.excludes || [],
-    format: options.format,
+    format: options.format || 'es5',
```
Comment (emilyrohrbough) [inline scripts/aggregate-translations/aggregate-translations.js:39]: Can we update
```diff
- fileSystem: options.outputFileSystem || config.outputFileSystem || fse,
+ fileSystem: config.outputFileSystem || fse,
```

if you look at how this option is used the aggregate-translation, this could not be provided by the CLI tool (and is not an option) because it would need to be passed as module.

**Review by emilyrohrbough — APPROVED** [review]

File: scripts/aggregate-translations/aggregate-translations-cli.js (hunk 1 above)
Comment (emilyrohrbough) [reply scripts/aggregate-translations/aggregate-translations-cli.js]: If this changes the CLI expectation, we might need to leave it as is until a MVB

Comment (nramamurth) [reply scripts/aggregate-translations/aggregate-translations-cli.js]: 💯 I shall revert the changes around these. 

Done: https://github.com/cerner/terra-toolkit/pull/265/commits/fb90652a1bb1e82f6820fabd9616629d569ae48f

File: scripts/aggregate-translations/aggregate-translations.js (hunk 2 above)
Comment (nramamurth) [reply scripts/aggregate-translations/aggregate-translations.js:39]: I'd leave it as-is because the `options` is not specific to CLI. The user could still use the [setup function](https://github.com/cerner/terra-toolkit/blob/master/docs/AggregateTranslations.md#setup-example) directly and pass the `outputFileSystem`, me thinks.

Comment (emilyrohrbough) [reply scripts/aggregate-translations/aggregate-translations.js:39]: Ah I see what you mean. 👍

**Review by emilyrohrbough — APPROVED** [review]

File: CHANGELOG.md [hunk 3]
```diff
@@ -10,6 +10,10 @@ Unreleased
 * Added a new method `validateElement` to both do a screenshot comparison and test accessibility
 * Log information on what selenium version is being used for the test run.
 
+### Fixed
+* Fixed the issue with Aggregate Translations CLI default options overriding the configuration file options.
+* Fixed an issue with the 'exclude' option in Aggregate Translations setup function.
```
Comment (StephenEsser) [inline CHANGELOG.md]: Can you add a short description about what issue was fixed for the exclude option?

Comment (bjankord) [reply CHANGELOG.md]: I'd recommend adding a link to the GitHub issue like so after the description.
```suggestion
* Fixed an issue with the 'exclude' option in Aggregate Translations setup function. [#264](https://github.com/cerner/terra-toolkit/issues/264)
```

**Review by bjankord — APPROVED** [review]

**Review by StephenEsser — APPROVED** [review]
