### PR TITLE
[terra-functional-testing] Fixing package name on Jenkins

### LINKED ISSUE #597: [terra-functional-testing] Fix packageName in reporter output file
# Bug Report

## Description

When run on Jenkins CI the spec reporter is generating the packageName as `app`. This function will need to make the necessary changes to ensure the packageName is parsed correctly when run on CI builds:

https://github.com/cerner/terra-toolkit/blob/05c4503e8f0b872c0a18c38ad8f49cbee3094013/packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js#L118-L125

## Steps to Reproduce

1. Choose a project running terra-functional-testing
2. Run the project on CI (in this case our internal Jenkins CI)
3. View the reporter artifacts from the Jenkins build
4. Observe the spec reporter outputs a file that contains a packageName key. This key should be the package name.

## Additional Context / Screenshots

On CI the project is likely being run in a directory that is colliding with the split operator. Either because it includes the `packages` string or because the current working directory is not what we are expecting. 

## Expected Behavior

The packageName should be the correct package name.

## Possible Solution

--

### PR DESCRIPTION
**Pull request by BenBoersma**
### Summary

Fixing packageName in reporter output file in Jenkins CI. 

Closes #597.

### Additional Details

@cerner/terra

[CONTRIBUTORS.md]: ../blob/main/CONTRIBUTORS.md
[License]: ../blob/main/LICENSE

### CODE REVIEW

File: packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js [hunk 1]
```diff
@@ -120,7 +120,12 @@ class SpecReporter extends WDIOReporter {
     if (spec.indexOf(`${path.sep}packages${path.sep}`) > -1) {
       return spec.split(`${path.sep}packages${path.sep}`).pop().split(path.sep)[0];
     }
-
+    const filepath = `${process.cwd()}${path.sep}package.json`;
```
Comment (yuderekyu) [inline packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js]: should we use join instead? it automatically normalizes the path
```suggestion
    const packageJsonPath = path.join(process.cwd(), 'package.json');
```

File: packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js [hunk 2]
```diff
@@ -120,7 +120,12 @@ class SpecReporter extends WDIOReporter {
     if (spec.indexOf(`${path.sep}packages${path.sep}`) > -1) {
       return spec.split(`${path.sep}packages${path.sep}`).pop().split(path.sep)[0];
     }
-
+    const packageJsonPath = path.join(process.cwd(), 'package.json');
+    if (fs.existsSync(filepath)) {
```
Comment (yuderekyu) [inline packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js]: oops, you'll have to update the path variable because my suggestion did not propagate beyond line 123

Comment (BenBoersma) [reply packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js]: Fixed here https://github.com/cerner/terra-toolkit/pull/613/commits/c8698e39c24fef876e728ae9139db62ed611116a

**Comment by benbcai** [comment]
Can we add a jest test [here](https://github.com/cerner/terra-toolkit/blob/main/packages/terra-functional-testing/tests/jest/reporters/spec-reporter/wdio-spec-reporter.test.js#L59) for this change?

**Comment by BenBoersma** [comment]
> Can we add a jest test [here](https://github.com/cerner/terra-toolkit/blob/main/packages/terra-functional-testing/tests/jest/reporters/spec-reporter/wdio-spec-reporter.test.js#L59) for this change?

test added and original test fixed https://github.com/cerner/terra-toolkit/pull/613/commits/c9d5dde6eab97ee77c5ad36981f3d4621c36f128#diff-f9e22fc833ee01164d37bc48bfebaf0b9466fe8ad9d4578469c143abc2a40f05R68

**Review by benbcai — APPROVED** [review]

**Review by StephenEsser — APPROVED** [review]

File: packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js [hunk 3]
```diff
@@ -120,7 +120,12 @@ class SpecReporter extends WDIOReporter {
     if (spec.indexOf(`${path.sep}packages${path.sep}`) > -1) {
       return spec.split(`${path.sep}packages${path.sep}`).pop().split(path.sep)[0];
     }
-
+    const packageJsonPath = path.join(process.cwd(), 'package.json');
+    if (fs.existsSync(packageJsonPath)) {
+      const jsonString = fs.readFileSync(packageJsonPath);
+      const packagejson = JSON.parse(jsonString);
+      return packagejson.name;
```
Comment (yuderekyu) [inline packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js]: on second thought, functional-testing already pulls in fs-extra, which has a [`readJsonSync`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/readJson-sync.md) method that reads and parses json. this requires us to replace our `fs` import with  `fs-extra`, what do you think?

```suggestion
      const { name } = fs.readJsonSync(packageJsonPath);
      return name;
```

Comment (BenBoersma) [reply packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js]: Yea i think that works. cuts down on the code a little and we already have fs-extra in the package so no reason not to.

Comment (BenBoersma) [reply packages/terra-functional-testing/src/reporters/spec-reporter/wdio-spec-reporter.js]: made the changes here, got a draft pr going to test the changes to make sure i didn't break anything
edit: helps if i include the commit link https://github.com/cerner/terra-toolkit/pull/613/commits/d9094f7156ee5f25aaf31a6a13fce40776f062db

**Review by mjhenkes — APPROVED** [review]
