### PR TITLE
Toolkit V4

### LINKED ISSUE #64: Clear diff and screen Directories before Running Screenshot Tests
# Issue Description
Each time the visual-regression service is ran, it captures screenshots in three locations:
- diff - the difference screenshot if the screenshot is out of mismatch tolerance
- reference - the checked in 'correct' screenshots
- screen - the screenshot from the last ran test

Before grabbing new screenshots, the diff and screen directories should be emptied such that it is clear which screenshots were truly grabbed in the last test run. 

Using the `specs` key, this cleanup is possible. I would recommend we create a new service or enhance the Terra Service to provide this functionality.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
All clean the diff and screen directories before creating new screenshots.

## Current Behavior
Currently the screenshots in the diff and screen directories are only updated if a new screenshot is taken, however, stale screenshot remain. This makes it challenging to shift through the relevant screenshots given if a screenshot comparison fails.

### LINKED ISSUE #69: Handle i18n in terra-toolkit
# Issue Description

Create the ability to test different locales within terra-toolkit.

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

We will want this to work in combination with parallelization.  Since we can't do this in Travis (you have to pay), and we want to limit resources, we will want the parallelization to be handled via running a very specific combination (e.g. pt-BR and small form factor) and then let the build system (e.g. jenkins) handle the parallelization.

## Current Behavior

N/A

### LINKED ISSUE #70: Support the ability to use parallelization in build systems that support it
# Issue Description

We want to support parallelization in build systems that support it (e.g. a private instance of Jenkins).  

## Issue Type

- [X] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Since we can't do this in Travis (you have to pay), and we want to limit resources, we will want the parallelization to be handled via running a very specific combination (e.g. pt-BR and small form factor) and then let the build system (e.g. Jenkins) handle the parallelization.

## Current Behavior

N/A

### LINKED ISSUE #96: Unable to install terra-toolkit
# Issue Description
I'm on Windows but using a Linux Subsystem for my React dev environment. I keep getting some kind of EINVAL -22 error 💣. The screenshot below says aggregate-translations.js but it also complains about other things in that bin folder.
image

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

It should be installed in peace.👍

## Current Behavior

N/A

## Steps to Reproduce

1. Open terminal 💻
2. Run <code>npm install terra-toolkit --save-dev</code> ⛏
3. Errors out after in the middle of the installation 💣

## Environment

* Component Version: 3.2.0
* Browser Name and Version: N/A
* Operating System and version (desktop or mobile): Desktop Windows 10, Linux Subsystem
* Node: v10.0.0
* npm: 5.6.0

### LINKED ISSUE #110: Webpack shareable config is not generating -webkit-flex styles
# Issue Description

CSS files generated through webpack by utilizing shareable webpack config provided by terra doesn't have -webkit-flex styles.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

CSS generated should have -webkit-flex styles.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version: terra-toolkit 3.4.0
* Browser Name and Version: PhantomJS
* Operating System and version (desktop or mobile):

### LINKED ISSUE #121: Disable css-loader minimize option, uses buggy version of cssnano that breaks themes
# Issue Description
In the current version of css-loader, if you run webpack in production mode, it will minimize the CSS with cssnano v3. The version of [cssnano included as a dependency](https://github.com/webpack-contrib/css-loader/blob/master/package.json#L18) in css loader [includes a bug](https://github.com/cssnano/cssnano/issues/450) which impacts long-hand CSS properties using CSS custom properties. A fix has supposedly been landed in cssnano v4-rc.2 release (need to test), but that release hasn't made it's way back into css-loader.

We don't see the issue in our default style, the issue is only present when setting values for CSS custom properties that are used in long-hand CSS styles

For example, given the following themable variables:

```css
:root {
    --terra-form-radio-outer-ring-border-style: solid;
    --terra-form-radio-focus-border-color: #88a8ef;
    --terra-form-radio-focus-border-width: 2px;
}
```

We get output incorrectly as the following from cssnano:

```css
:root {
  border: 2px solid #88a8ef;
}
```

### Attempted fix
We've got around this before by converting the source code to short-hand. This way cssnano doesn't do any conversion on the style.

e.g `border: var(--border-style, 1px solid #f00);`

### Sub issue
However, this causes a problem with styles that could be bidirectional.

For example, we break out padding and margin into individual styles for bidi reasons.

```css
   padding-bottom: var(--terra-tag-padding-bottom, 0.1428rem);
   padding-left: var(--terra-tag-padding-left, 0.5rem);
   padding-right: var(--terra-tag-padding-right, 0.5rem);
   padding-top: var(--terra-tag-padding-top, 0.1428rem);
```
This seems to make it easier for the postcss-rtl plugin to apply `[dir="ltr"]` and `[dir="rtl"]` selectors to the left and right padding.

It seems like we've run into issues in the past with setting padding to use short-hand property syntax and bidi styling like below:

```css
padding: var(--terra-select-padding-top, 0) var(--terra-select-padding-right, 0) var(--terra-select-padding-bottom, 0) var(--terra-select-padding-left, 0); 
```
My guess is the postcss-rtl plugin doesn't parse / understand the css custom property values or it may see the values are set to a nuetral, non-bidi necessary value like 0 and opt-out of creating `[dir="ltr"]` and `[dir="rtl"]` selectors. This is fine until someone themes one of the left or right padding values to be something other than 0, then there theme doesn't not work bidirectionaly.

@JakeLaCombe is likely more familiar with the details on the bidi styles issue.

### Proposal
I'd recommend we disable the `minimize` option in the css-loader to opt-out of cssnano behavior until css-loader updates to use cssnano v4.

Using the sass-loader, CSS is already minified when webpack is run in production mode. cssnano offers a more desctructive minimization that I don't find to be completely neccessary with our current webpack setup.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Theming styles work and theming and bidirectionality styling work together.

### PR DESCRIPTION
**Pull request by emilyrohrbough**
### Summary

- Added these config options for i18n Support (Resolves #69) and for paralyzation support (Resolves #70). Adding these options all for paralyzed container test runs (think Jenkins).
    - `locale` - the locale to serve the site in. This is used by ServeStatic service to set the locale on the served site and it is used by the visual regression config for screenshot output.
    - `formFactor` - the terra viewport for the test run. This is used by the visual regression config for screenshot output.
    - `baseScreenshotDir` - used by the visual regression config to change where snapshots are stored. This options is added for test reusability such that reused visual regression tests will not output screenshots in node_modules.

- Added tt-wdio bin script called `tt-wdio` which runs wdio test runs for the specified locales and form factors. This allows for locale test runs that can match  paralyzed container test runs by concurrently running the wdio  for each test run variation. By default `tt-wdio` runs like wdio-cli out of the box by running the default locale and form factor (if defined). 

- **BREAKING CHANGE** Update screenshot naming to organize screenshots by locale and form factor. 
    - changed `screen` directory name to `latest` to remove confusion on the most recent screenshot(s) taken. Must update .gitignore to include this dir.
```
// New screenshot pattern
{reference|latest|diff}/locale/browser_formFactor/testSuite/describeBlockTitle[screenshotName].png

// Current screenshot pattern
{reference|screen|diff}/browser/describeBlockTitle[screenshotName].widthxheight.png
```

Additionally added automatic screenshot name shortening to allow for descriptive describes, but short screenshot names. Add `[ ]`s around the desired key word(s) for the shorter name. For example:

```
// example-spec.js
cont viewports = Terra.getViewports('tiny');
describe('This is a long screenshot name for an [example test], () => {
      Terra.should.matchScreenshot({ viewports });
});

// New screenshot result
reference/en/chrome_tiny/example/example_test[default].png

// Current screenshot result
reference/chrome/This_is_a_long_screenshot_name_for_an_[example_test][default].470x768.png
```

- Added clean-screenshots bin script called `tt-clean-screenshot` which will remove `screen`, `latest`, and `diff` directories by default and when passing `--removeReference` will also remove `reference` dirs. (Resolves #64)

- EDIT: REMOVED default `browserslist`, `eslint` and `stylelint` configurations in favor of moving these configurations to their own package to align with browserslist and eslint standards.

- Bumped dependencies. 
    - [Axe Changes](https://github.com/dequelabs/axe-core/releases) We will need to disable the `region` rule in terra repos.

- **BREAKING CHANGE** Changed bin scripts from `tt:script_name` to `tt-script_name`. The use of `:` breaks windows. (Resolves #96)

### To DO:
- [x] ~Write Docs~
- [x] ~Bump Dependencies~

### Update
Fixes #121

### CODE REVIEW

File: scripts/wdio/wdio-runner-cli.js [hunk 1]
```diff
@@ -0,0 +1,69 @@
+#!/usr/bin/env node
+
+const commander = require('commander');
+const getWdioConfigPath = require('./getWdioConfigPath');
+const cleanScreenshots = require('./clean-screenshots');
+const runner = require('./wdio-runner');
+
+const packageJson = require('../../package.json');
+
+// WDIO ALLOWED ARGUMENTS... Do we want to wrap. My vote, no. IF YES, the args we might support are commented below.
```
Comment (emilyrohrbough) [inline scripts/wdio/wdio-runner-cli.js]: Thoughts?

File: package.json [hunk 2]
```diff
@@ -23,9 +23,11 @@
...
   },
   "bin": {
-    "tt:aggregate-translations": "bin/aggregate-translations.js",
-    "tt:serve": "bin/serve.js",
-    "tt:serve-static": "bin/serve-static.js"
+    "tt-aggregate-translations": "bin/aggregate-translations.js",
+    "tt-clean-screenshots": "bin/clean-screenshots.js",
+    "tt-serve": "bin/serve.js",
+    "tt-serve-static": "bin/serve-static.js",
+    "tt-wdio": "bin/tt-wdio.js"
```
Comment (BenBoersma) [inline package.json]: I can confirm that these changes fix the issue windows was having with the bin about "tt:serve" not existing.

File: config/webpack/webpack.config.js [hunk 3]
```diff
@@ -53,11 +53,14 @@ const defaultWebpackConfig = (env = {}, argv = {}) => {
                 return [
                   Autoprefixer({
```
Comment (emilyrohrbough) [inline config/webpack/webpack.config.js]: Once the `browserslist-config-terra` package is released, it will be added as a dependency and this list will be updated to use the list provided in `browserslist-config-terra`. It will be one-to-one so this is not a blocker.

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+- load-json-file: `^2.0.0` -> `^5.0.0`
+- postcss-assets-webpack-plugin: `^1.1.0` -> `^2.0.0`
+- postcss-custom-properties: `^6.0.1` -> `^7.0.0`
+- sass-loader: `^6.0.6` -> `^7.0.1`
+
+
+
+
+## WebdriverIO
+Terra Toolkit's configuration and services now have i18n and paralyzation support. These included new config options, as well as changes to screenshot naming to organize screenshots by locale and form factor.
```
Comment (nfaltermeier) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: ~~paralyzation~~ *parallelization*

File: scripts/wdio/README.md [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+| **--formFactors**  | `undefined` | The list of viewport sizes to test. |
+| **-locales** | `['en']` | The list of locales to test. |
+| **--continueOnFail** | `undefined` | Whether or not to execute all test runs when a run fails. |
+| **--useSeleniumGrid** |`false` | Whether or not the USE_SELENIUM_GRID process env should be set. |
+| **--updateReference** | `undefined` | Whether or not to remove reference screenshots during screenshot cleanup. CLI use only. |
+| **--port**  | `undefined` | [wdio option] The selenium server port. |
+| **--host** | `undefined` | [wdio option] The selenium server host address. |
+| **--baseUrl** | `undefined` | [wdio option] The base URL. |
+| **--suite** | `undefined  ` | [wdio option] The suite to run. |
+| **--suite** | `undefined` | [wdio option] The spec file to run. |
```
Comment (tomleewu) [inline scripts/wdio/README.md]: Should be **--spec** instead of **--suite**

File: scripts/wdio/README.md [hunk 6]
```diff
@@ -0,0 +1,74 @@
+# Terra Toolkit Wdio Helpers
+
+## Wdio Runner
+Terra Toolkit offers its own wdio test runner which runs wdio test runs for specified locales and form factors. This allows for locale test runs that can match paralyzed container test runs by concurrently running the wdio for each test run variation. This runner is a replacement for webdriver's bin script `wdio` by directly calling Webdriver's test launcher module for each test variation.
```
Comment (tomleewu) [inline scripts/wdio/README.md]: ~~paralyzed~~ _parallelized_

File: scripts/wdio/wdio-runner-cli.js [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+const listOptions = list => (list.replace(/[\[\]\s]/g, '').split(',').map(String));
+
+// Parse process arguments
+commander
+  .version(packageJson.version)
+  .option('--config <path>', 'The wdio config path for the tests', undefined)
+  .option('--formFactors <list>', 'The list of viewport sizes to test', listOptions, undefined)
+  .option('--locales <list>', 'The list of locales to test', listOptions, ['en'])
+  .option('--useSeleniumGrid', 'Whether or not the USE_SELENIUM_GRID process env should be set', false)
+  .option('--continueOnFail', 'Wheather or not to execute all test runs when a run fails')
```
Comment (tomleewu) [inline scripts/wdio/wdio-runner-cli.js]: Should `'--continueOnFail'` have a default value `undefined`?

File: scripts/serve/serve-static.js [hunk 8]
```diff
@@ -55,36 +65,54 @@ const virtualApp = (site, index, fs) => {
...
+      const langPattern = /lang="[a-zA-Z0-9-]*"/;
+      const langLocale = `lang="${locale}"`;
+
+      const isLanguageSet = fileContent.match(langPattern);
+
+      // Set the test locale for the file
+      if (isLanguageSet) {
+        fileContent = fileContent.replace(langPattern, langLocale);
+      } else {
+        fileContent = fileContent.replace(/<html/, `<html ${langLocale}`);
```
Comment (noahbenham) [inline scripts/serve/serve-static.js]: This might be dangerously assuming that only html pages will be served, which isn't always the case. We're serving mock avatar assets with serve-static, for example.

File: scripts/serve/README.md [hunk 9]
```diff
@@ -18,12 +18,12 @@ Serve is offered up as both a cli and a javascript function.
 | **-p, --production** | false | false | Passes the -p flag to the webpack config. |
 | **--host** | false |`undefined` | Sets the host that the server will listen on. eg. '10.10.10.1' |
 
-If no config is supplied tt:serve will first search for `webpack.config.js` in the working directory, if that is not found it will attempt to use the default webpack config supplied by terra-dev-site.
+If no config is supplied tt-serve will first search for `webpack.config.js` in the working directory, if that is not found it will attempt to use the default webpack config supplied by terra-dev-site.
```
Comment (noahbenham) [inline scripts/serve/README.md]: nit, grammar: `working directory, if` -> `working directory. If`

File: package.json [hunk 10]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "terra-toolkit",
-  "version": "3.6.0",
+  "version": "3.5.0",
```
Comment (noahbenham) [inline package.json]: Should this be `4.0.0`?

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 11]
```diff
@@ -0,0 +1,101 @@
...
+
+1) The updated screenshot pattern is:
+
+```
+{reference|latest|diff}/locale/browser_formFactor/testSuite/describeBlockTitle[screenshotName].png
+```
+
+2. The screenshot output directory name `screen` was changed to `latest` to remove confusion on that this directory contained the most recent screenshot(s) taken.
+
+3. Screenshot names will now be shorten to allow for descriptive describes when `[]`s are around the desired key word(s) to save shorter screenshot names. For example:
```
Comment (noahbenham) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: 1. `shorten` -> `shortened`
2. Remove `to save shorter screenshot names`

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 12]
```diff
@@ -0,0 +1,101 @@
...
+```
+// example-spec.js
+cont viewports = Terra.getViewports('tiny');
```
Comment (noahbenham) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: `const`

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 13]
```diff
@@ -0,0 +1,101 @@
...
+#### Screenshot Naming
+The default visual-regression configuration was enhanced in these ways to organize screenshots by locale and form factor. These enhancements were:
+
+1) The updated screenshot pattern is:
+
+```
+{reference|latest|diff}/locale/browser_formFactor/testSuite/describeBlockTitle[screenshotName].png
+```
+
+2. The screenshot output directory name `screen` was changed to `latest` to remove confusion on that this directory contained the most recent screenshot(s) taken.
```
Comment (noahbenham) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: `on that this directory contained` -> `about which directory contains`

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 14]
```diff
@@ -0,0 +1,101 @@
...
+### WebdriverIO Configuration
+The following configuration options were added:
+- `locale` - the locale to serve the site in. By default this is `en`.
+- `formFactor` - the terra viewport for the test run. By default, the viewport is determined the current browser size.
+- `baseScreenshotDir` - where snapshots are stored. By default, this will be the test-spec directory.
+
+No updates are required with the addition of the config options.
+
+#### Screenshot Naming
+The default visual-regression configuration was enhanced in these ways to organize screenshots by locale and form factor. These enhancements were:
```
Comment (noahbenham) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: `enhanced in these ways to` -> `enhanced to`

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 15]
```diff
@@ -0,0 +1,101 @@
...
+- load-json-file: `^2.0.0` -> `^5.0.0`
+- postcss-assets-webpack-plugin: `^1.1.0` -> `^2.0.0`
+- postcss-custom-properties: `^6.0.1` -> `^7.0.0`
+- sass-loader: `^6.0.6` -> `^7.0.1`
+
+
+
+
+## WebdriverIO
+Terra Toolkit's configuration and services now have i18n and parallelization support. These included new config options, as well as changes to screenshot naming to organize screenshots by locale and form factor.
```
Comment (noahbenham) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: `included` -> `include`

File: scripts/serve/serve-static.js (hunk 8 above)
Comment (noahbenham) [reply scripts/serve/serve-static.js]: Nope, the only "custom" thing we're serving (right now at least) is images. Just wanted to make sure this wouldn't break anything, it might be fine as-is.

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 16]
```diff
@@ -0,0 +1,101 @@
...
+
+### Dependencies Updates
+The following dependencies were updated in Terra toolkit's default webpack configuration:
+
+- autoprefixer: `^6.7.7` -> `^8.5.2`
+- load-json-file: `^2.0.0` -> `^5.0.0`
+- postcss-assets-webpack-plugin: `^1.1.0` -> `^2.0.0`
+- postcss-custom-properties: `^6.0.1` -> `^7.0.0`
+- sass-loader: `^6.0.6` -> `^7.0.1`
+
```
Comment (ryanthemanuel) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md:52]: Lots of blank spaces here.  Not a big deal.

File: package.json (hunk 10 above)
Comment (ryanthemanuel) [reply package.json]: Not yet (until we release it)

Comment (noahbenham) [reply package.json]: Downgrading seemed odd to me

File: tests/test.config.func.js [hunk 17]
```diff
@@ -0,0 +1,54 @@
+const path = require('path');
+const HtmlWebpackPlugin = require('html-webpack-plugin');
+
+// eslint-disable-next-line no-unused-vars
+const webpackConfig = (env = {}, argv = {}) => ({
+  entry: {
+    index: path.join(__dirname, 'fixtures', 'index'),
+  },
+  plugins: [
+    new HtmlWebpackPlugin({
```
[the remark this answers is not in the document]
Comment (emilyrohrbough) [reply tests/test.config.func.js]: Possibly, but since this a 1-to-1 copy of `test.config.js` I will update this to import that configuration. This file was added to ensure the tests were started as expected when using either a webpack config object or function.

File: package.json (hunk 10 above)
Comment (emilyrohrbough) [reply package.json]: This PR has been out for quite a while. The downgrade happened because we've had a release since this PR was put out. I will update.

**Review by ryanthemanuel — APPROVED** [review]

**Review by BenBoersma — APPROVED** [review]

File: bin/tt-wdio.js [hunk 18]
```diff
@@ -0,0 +1,3 @@
+#!/usr/bin/env node
```
Comment (mjhenkes) [inline bin/tt-wdio.js]: Lets be consistent about file naming and just name this wdio.js

File: config/wdio/visualRegressionConf.js [hunk 19]
```diff
@@ -0,0 +1,86 @@
+const path = require('path');
+const LocalCompare = require('wdio-visual-regression-service/compare').LocalCompare;
```
Comment (mjhenkes) [inline config/wdio/visualRegressionConf.js]: prefer destructuring 😜

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 20]
```diff
@@ -0,0 +1,101 @@
+# Terra Toolkit Upgrade Guide v4.0.0
+This document will provide information on upgrading from terra-toolkit 3.x to 4.0.0.
+
+## Terra Scripts
+The scripts provided by Terra Toolkit v3 used `tt:` prefixes. It was found `:` causes incorrect .bin generation on windows devices so these scripts have been updated to use the prefix `tt-`.
```
Comment (tomleewu) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: nit: Capitalize "Windows"

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 21]
```diff
@@ -0,0 +1,101 @@
...
+});
+
+// v4 screenshot result
+reference/en/chrome_tiny/example/example_test[default].png
+
+// v3 screenshot result
+reference/chrome/This_is_a_long_screenshot_name_for_an_[example_test][default].470x768.png
+```
+
+4. Screenshot names will now remove windows reserve character to prevent installation failures.
```
Comment (tomleewu) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: nit: Capitalize "Windows"

File: CHANGELOG.md [hunk 22]
```diff
@@ -3,6 +3,23 @@ Changelog
...
+### Changed    
+* **BREAKING CHANGE** Update screenshot naming to organize screenshots by locale and form factor
+    - changed `screen` directory name to `latest`
+    - added automatic screenshot name shortening to allow for descriptive describes, but short screenshot names.
+    - ensure screenshot naming does not contain windows
+* **BREAKING CHANGE** Bumped dependencies.
+* Update the default webpack.config's Autoprefixer's browserslist values
+
+### Fixed
+* **BREAKING CHANGE** Changed bin scripts from `tt:script_name` to `tt-script_name`. The use of `:` breaks windows. See https://msdn.microsoft.com/en-us/library/ms832054.aspx.
```
Comment (tomleewu) [inline CHANGELOG.md]: nit: Capitalize "Windows"

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 23]
```diff
@@ -0,0 +1,101 @@
...
+Terra Toolkit now offers a screenshot cleanup tool to remove `errorScrenshots`, `latest`, `diff` and, if indicated, `reference` screenshots.
+
+This is available via the `tt-clean-screenshots` cli or the `clean-screenshots` javascript function.
+
+###### For more information about terra-wdio and clean-screenshots and for setup examples please go [here](https://github.com/cerner/terra-toolkit/tree/master/scripts/wdio).
+
+
+## Webpack Configuration
+### Configuration Changes
+The browsers list provided to the Autoprefixer plugin were updated to:
```
Comment (mjhenkes) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: This should be changed to refer to the terr browerlist repo

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 24]
```diff
@@ -0,0 +1,101 @@
...
+
+##### How to Get These Changes
+1. Delete your reference screenshots
+2. Run your wdio tests
+3. Add `**/wdio/__snapshots__/latest` to your `.gitignore`
+
+**NOTE:** The default visual-regression config file has moved from `terra-toolkit/lib/wdio/visualRegressionConf.js` to `terra-toolkit/config/wdio/visualRegressionConf.js`. This change was made to provide a consistent location for our reusable configuration files.
+
+### AxeService
+The `axe-core` dependency was updated from `^6.7.7` to `^3.0.2`.
```
Comment (mjhenkes) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: ~^6.7.7~ ^2.6.1

File: scripts/serve/serve-static.js (hunk 8 above)
Comment (mjhenkes) [reply scripts/serve/serve-static.js]: Lets only do this replace if the file extension is .html. This may get confusing to consumers since normal web servers don't manipulate the files they're serving. At a minimum lets also add a comment to the file we're manipulating explaining where this file came from. Also break this logic out into it's own function this function is getting to long.

File: scripts/serve/serve-static.js [hunk 25]
```diff
@@ -55,36 +65,54 @@ const virtualApp = (site, index, fs) => {
...
       next();
     }
   });
 
-  app.use((req, res, next) => {
-    const err = new Error(`Not Found: ${req.originalUrl}`);
-    err.status = 404;
-    next(err);
-  });
+  if (verbose) {
```
Comment (mjhenkes) [inline scripts/serve/serve-static.js:110]: 👍

File: config/wdio/visualRegressionConf.js [hunk 26]
```diff
@@ -0,0 +1,86 @@
...
+
+function getFormFactor(context) {
+  let formFactor = global.browser.options.formFactor;
+
+  if (!formFactor) {
+    const browserWidth = context.meta.viewport.width;
+    const viewportSizes = Object.keys(viewports);
+    for (let i = 0; i < viewportSizes.length; i += 1) {
+      const viewport = viewportSizes[i];
+      if (browserWidth <= viewports[viewport].width) {
```
Comment (nfaltermeier) [inline config/wdio/visualRegressionConf.js]: We should probably either add a fallback incase the browserWidth is greater than our biggest viewport, in which case `formFactor` would be undefined, or explicitly throw an error.

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 27]
```diff
@@ -0,0 +1,101 @@
...
+- autoprefixer: `^6.7.7` -> `^8.5.2`
+- load-json-file: `^2.0.0` -> `^5.0.0`
+- postcss-assets-webpack-plugin: `^1.1.0` -> `^2.0.0`
+- postcss-custom-properties: `^6.0.1` -> `^7.0.0`
+- sass-loader: `^6.0.6` -> `^7.0.1`
+
+
+
+
+## WebdriverIO
```
[the remark this answers is not in the document]
Comment (emilyrohrbough) [reply docs/TerraToolkitUpgradeGuide-v4.0.0.md]: IMO I do not want to advertise this as a change. It would be better if projects followed the same package structure. However, if others feel this should be included I can add it.

File: scripts/wdio/wdio-runner.js [hunk 28]
```diff
@@ -0,0 +1,49 @@
...
+    for (let factor = 0; factor < factors.length; factor += 1) {
+      let envValues = `LOCALE=${locale} `;
+
+      const form = factors[factor];
+      if (form) {
+        process.env.FORM_FACTOR = form;
+        envValues += `FORM_FACTOR=${form}`;
+      }
+
+      // eslint-disable-next-line no-console
```
[the remark this answers is not in the document]
Comment (mjhenkes) [reply scripts/wdio/wdio-runner.js:22]: No, we should target this so that we're very explicit about when we're disabling eslint. I don't want the next guys to edit this file to just add console logs every where.

File: config/wdio/visualRegressionConf.js [hunk 29]
```diff
@@ -0,0 +1,86 @@
...
+  const locale = global.browser.options.locale || 'en';
+  const browserName = context.desiredCapabilities.browserName;
+  const formFactor = getFormFactor(context);
+  const testForm = `${browserName}_${formFactor}`;
+  const testSuite = path.parse(context.test.file).name;
+
+  return path.join(refDir, locale, testForm, testSuite);
+}
+
+function getScreenshot(ref) {
```
Comment (nfaltermeier) [inline config/wdio/visualRegressionConf.js]: Maybe this could be better named `GetAbsoluteScreenshotPath` or something similar?

File: scripts/wdio/wdio-runner.js [hunk 30]
```diff
@@ -0,0 +1,49 @@
+const Launcher = require('webdriverio').Launcher;
+
+async function wdioRunner(options) {
+  const {
+    configPath, locales, formFactors, useSeleniumGrid, continueOnFail, ...testSetup
+  } = options;
+  const factors = formFactors || [undefined];
+
+  process.env.USE_SELENIUM_GRID = useSeleniumGrid;
```
Comment (mjhenkes) [inline scripts/wdio/wdio-runner.js]: Should we keep this separate from this script? It seems like an implementation leak.

`USE_SELENIUM_GRID='true' tt-wdio --config ./wdio.conf.js --locales ['en','es']`
vs.
`tt-wdio --config./wdio.conf.js --locales ['en','es'] --useSeleniumGrid true`

File: config/wdio/visualRegressionConf.js [hunk 31]
```diff
@@ -0,0 +1,86 @@
...
+        formFactor = viewports[viewport].name;
+        break;
+      }
+    }
+  }
+
+  return formFactor;
+}
+
+function getScreenshotPath(ref, context) {
```
Comment (nfaltermeier) [inline config/wdio/visualRegressionConf.js]: I don't think `ref` is a very descriptive variable name in these couple of methods. Maybe `screenshotType` or `screenshotCategory` would be better.

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md (hunk 27 above)
[the remark this answers is not in the document]
Comment (yuderekyu) [reply docs/TerraToolkitUpgradeGuide-v4.0.0.md]: I can see either - there could potentially be consumers who had a need for custom specs, but couldn't with the last major release. Pretty indifferent though.

File: README.md [hunk 32]
```diff
@@ -34,14 +33,6 @@ Terra Toolkit uses docker to setup, run, and tear down selenium to ensure a cons
 
 See the [Webdriver.io Utility Developer's Guide](https://github.com/cerner/terra-toolkit/blob/master/docs/Wdio_Utility.md) to get started.
 
-## Nightwatch Utility
```
[the remark this answers is not in the document]
Comment (emilyrohrbough) [reply README.md:37]: I am going to move forward with removing this documentation from the main README. This functionality has been deprecated for a long time and removing the docs here will remove the potential for a new user to want to use it. The nightwatch documentation still exists [here](https://github.com/cerner/terra-toolkit/blob/master/docs/Nightwatch_Utility.md) for now.

File: scripts/wdio/wdio-runner.js (hunk 30 above)
Comment (emilyrohrbough) [reply scripts/wdio/wdio-runner.js]: hmmm I see what you mean. I will remove `useSeleniumGrid` script option in favor of passing the env var directly.

File: config/wdio/visualRegressionConf.js (hunk 26 above)
Comment (emilyrohrbough) [reply config/wdio/visualRegressionConf.js]: If a viewport is larger than a terra defined viewport, it will be returned as `undefined` and the form dir will then be named `undefined`. This will not break tests. 

I have two thoughts with this,

1. we either check and set the fallback to `enormous` 
2. we do not provide a fallback because this screensize is larger than a terra-defined viewport.

For now, I will update to fallback to `enormous` as this is verifies that at an overlay large viewport, the page/element/etc renders as expected. However, I what are other's opinions on providing this fallback?

@mjhenkes @bjankord @ryanthemanuel @JakeLaCombe

**Review by dkasper-was-taken — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

File: docs/TerraToolkitUpgradeGuide-v4.0.0.md [hunk 33]
```diff
@@ -0,0 +1,98 @@
...
+### Serve
+The `webpack-serve` dependency was updated from `^0.3.1` to `^1.0.2`.
+
+### Wdio Runner
+Terra Toolkit now offers its own wdio test runner which runs wdio test runs for specified locales and form factors. This allows for locale test runs that can match parallelized container test runs by concurrently running the wdio for each test run variation. This runner is a replacement for webdriver's bin script `wdio` by directly calling Webdriver's test launcher module for each test variation.
+
+Terra's wdio test runner is available via the `tt-wdio` cli or the `wdio-runner` javascript function.
+
+### Clean Screenshots
+Terra Toolkit now offers a screenshot cleanup tool to remove `errorScrenshots`, `latest`, `diff` and, if indicated, `reference` screenshots.
```
Comment (JakeLaCombe) [inline docs/TerraToolkitUpgradeGuide-v4.0.0.md]: `errorScreenshots`

**Review by saedar — APPROVED** [review]

**Review by JakeLaCombe — APPROVED** [review]

File: .eslintrc [hunk 34]
```diff
@@ -10,5 +10,6 @@
   },
   "rules": {
     "max-len": "off", // Remove warnings on max line length exceeding 100 characters
+    "prefer-destructuring": "off"
```
Comment (bjankord) [inline .eslintrc:13]: Curious, why turn this off?

File: config/wdio/visualRegressionConf.js [hunk 35]
```diff
@@ -0,0 +1,89 @@
...
+function createTestName(fullName) {
+  const matches = testIdRegex.exec(fullName);
+
+  // If test ID is provided, use the ID for a shorter test name, otherwise use the full name
+  let name = matches ? matches[1] : fullName.trim();
+
+  // Remove white space
+  name = name.replace(/[\s+.]/g, '_');
+
+  // Remove windows reserved characters. See: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions
```
Comment (bjankord) [inline config/wdio/visualRegressionConf.js:22]: Nice

File: package.json [hunk 36]
```diff
@@ -45,67 +50,77 @@
     "release:major": "node scripts/release/release.js major",
     "release:minor": "node scripts/release/release.js minor",
     "release:patch": "node scripts/release/release.js patch",
-    "test": "npm run jest && npm run compile && npm run nightwatch && npm run nightwatch:port-provided && wdio wdio.conf.js",
-    "wdio": "wdio wdio.conf.js"
+    "test": "npm run jest && npm run nightwatch && npm run nightwatch:port-provided && npm run wdio",
+    "wdio": "npm run wdio-webpack-obj && npm run wdio-webpack-func && npm run tt-wdio-webpack-obj && npm run tt-wdio-webpack-func",
+    "wdio-webpack-obj": "wdio",
+    "wdio-webpack-func": "TT_TEST_WDIO_FUNCTION=true wdio",
```
Comment (bjankord) [inline package.json:56]: Curious, what do the following scripts do:`wdio-webpack-func` and `tt-wdio-webpack-func`?

File: package.json [hunk 37]
```diff
@@ -45,67 +50,77 @@
     "release:major": "node scripts/release/release.js major",
     "release:minor": "node scripts/release/release.js minor",
     "release:patch": "node scripts/release/release.js patch",
-    "test": "npm run jest && npm run compile && npm run nightwatch && npm run nightwatch:port-provided && wdio wdio.conf.js",
-    "wdio": "wdio wdio.conf.js"
+    "test": "npm run jest && npm run nightwatch && npm run nightwatch:port-provided && npm run wdio",
+    "wdio": "npm run wdio-webpack-obj && npm run wdio-webpack-func && npm run tt-wdio-webpack-obj && npm run tt-wdio-webpack-func",
+    "wdio-webpack-obj": "wdio",
```
Comment (bjankord) [inline package.json:55]: What's the idea behind this script name / script usage?

File: package.json [hunk 38]
```diff
@@ -45,67 +50,77 @@
...
+    "wdio-webpack-func": "TT_TEST_WDIO_FUNCTION=true wdio",
+    "tt-wdio-webpack-obj": "node scripts/wdio/wdio-runner-cli.js",
```
Comment (bjankord) [inline package.json:57]: What's the idea behind this script name / script usage?

File: package.json [hunk 39]
```diff
@@ -45,67 +50,77 @@
...
+    "tt-wdio-webpack-func": "TT_TEST_WDIO_FUNCTION=true node scripts/wdio/wdio-runner-cli.js"
   },
   "dependencies": {
     "async": "^2.5.0",
-    "autoprefixer": "^6.7.7",
-    "axe-core": "^2.6.1",
+    "autoprefixer": "^8.5.2",
```
Comment (emilyrohrbough) [inline package.json:62]: @bjankord @mjhenkes @ryanthemanuel @JakeLaCombe One thing to note with bumping "autoprefixer", when run compile:prod, the `css-loader` will be used to minify our css and this uses `cssnano`, which pulls in the autoprefixer version 6.7.7.... Realized some dependency difference on https://github.com/cerner/terra-clinical/pull/358 (long post there). Just to be aware or possible wait on?

**Review by bjankord — APPROVED** [review]

File: package.json (hunk 39 above)
Comment (bjankord) [reply package.json:62]: I'm ok with keeping autoprefixer on `^6.0.0` until cssnano v4 is released. I think it would be good to reach out to the maintainers on that and see if we can get an idea when it may be released. 

I've run into another bug today with cssnano around how it minifies long hand CSS properties that are used with css custom properties. The "fix" was to turn `minimize` off in the css-loader options. Seeing as cssnano is causing issues now in multiple places, I'd like to discuss disabling the minimize option that triggers cssnano in our webpack config until cssnano v4 is released and consumed in the css-loader. The sass-loader already does a decent job of minification when webpack is run in prod mode. I can [log an issue](https://github.com/cerner/terra-toolkit/issues/121) to kick off the discussion.

Its dissappointing to hear v3 cssnano's dependencies are they way they are and break our use of browserlist.

Comment (mjhenkes) [reply package.json:62]: It seems they've been working on v4 for some time. https://github.com/cssnano/cssnano/issues/408

**Review by nfaltermeier — APPROVED** [review]

File: package.json (hunk 36 above)
Comment (emilyrohrbough) [reply package.json:56]: We can take both a webpack obj and webpack function as configuration that we pass to the webpack compiler. When passing an object, we have to clone it before setting the webpack ouptut dir https://github.com/cerner/terra-toolkit/pull/113/files#diff-2d0e39e2b5431dc8d9df655f5fc376fbR49

Comment (emilyrohrbough) [reply package.json:56]: These scripts are testing webpack configuration passed as a function which is toggle in wdio.config [here](https://github.com/cerner/terra-toolkit/pull/113/files#diff-c2b12f3e29d36b46344876dbf97bd0f8R6)

File: package.json (hunk 37 above)
Comment (emilyrohrbough) [reply package.json:55]: These scripts are testing webpack configuration passed as a object which is toggle in wdio.config here

File: package.json (hunk 39 above)
Comment (emilyrohrbough) [reply package.json:62]: Talked offline. The consensus was to keep the autoprefixer bump and disable minification via the css-load until cssnano v4 is released

**Review by tomleewu — APPROVED** [review]
